name: ftemplate
description: "A flutter template for personal use."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  mocktail: ^1.0.4
  husky: ^0.1.7
  commitlint_cli: ^0.8.1

flutter:
  uses-material-design: true
  generate: true

# internal packages
workspace:
  - packages/common/app_launcher
  - packages/common/app_logger
  - packages/common/app_utils
  - packages/common/storage

  - packages/platform/permission_client
  - packages/platform/package_info_client

  - packages/deep_link_client/deep_link_client
