name: package_info_client
description: "A client that provides information about the app's package metadata."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
# package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
