name: permission_client
description: "A client that handles requesting permissions on a device."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
