name: app_logger
description: "A structured logging package for Flutter applications with console, file, and remote logging capabilities."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  intl: ^0.20.2
  logger: ^2.6.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
