name: storage
description: "A simple and secure local storage package for school management systems with support for primitives, collections, and JSON serialization."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
