name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Runs on PRs and main/develop branches
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'screenshots/**'
      - '.gitignore'
      - '.vscode/**'
      - '.husky/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'screenshots/**'
      - '.gitignore'
      - '.vscode/**'
      - '.husky/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v6

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.x'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: ğŸ“¦ Install Dependencies
        run: flutter pub get

      # Code generation if needed
      - name: Code Generation
        run: |
          # Run build_runner for all packages in the workspace that have build_runner as a dependency
          git ls-files '**/pubspec.yaml' | xargs grep -l "build_runner" | xargs -I {} dirname {} | while read dir; do
            echo "Building in $dir..."
            (cd "$dir" && dart run build_runner build --delete-conflicting-outputs)
          done

      - name: âœ¨ Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: ğŸ•µï¸ Analyze
        run: flutter analyze lib test
